FROM oven/bun:alpine

WORKDIR /app

COPY package.json bun.lock tsconfig.base.json turbo.json ./
COPY packages ./packages
COPY apps ./apps

RUN bun install --frozen-lockfile

EXPOSE 3001

CMD ["bun", "run", "--cwd", "apps/api", "start"]
